runtime: python310 

env_variables:
  NODE_ENV: 'production'

instance_class: F2

handlers:
  - url: /static
    static_dir: build/static

  - url: /static/js
    static_dir: build/static/js

  - url: /static/css
    static_dir: build/static/css

  - url: /static/media
    static_dir: build/static/media

  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico

  - url: /logo192.png
    static_files: build/logo192.png
    upload: build/logo192.png

  - url: /logo512.png
    static_files: build/logo512.png
    upload: build/logo512.png

  - url: /manifest.json
    static_files: build/manifest.json
    upload: build/manifest.json

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
