# Spezifiziert die verwendete Laufzeitumgebung für die App
runtime: python310

# Definiert Umgebungsvariablen
env_variables:
  NODE_ENV: 'production'  # Setzt die Node-Umgebung auf Produktion

# Definiert die Instanzklasse, die für die Anwendung verwendet wird
instance_class: F2

# Handler für die verschiedenen URL-Pfade und statischen Dateien
handlers:
  # Handler für den statischen Ordner
  - url: /static
    static_dir: build/static  # Verweist auf das Verzeichnis build/static

  # Handler für statische JavaScript-Dateien
  - url: /static/js
    static_dir: build/static/js  # Verweist auf das Verzeichnis build/static/js

  # Handler für statische CSS-Dateien
  - url: /static/css
    static_dir: build/static/css  # Verweist auf das Verzeichnis build/static/css

  # Handler für statische Mediendateien
  - url: /static/media
    static_dir: build/static/media  # Verweist auf das Verzeichnis build/static/media

  # Handler für die favicon.ico Datei
  - url: /favicon.ico
    static_files: build/favicon.ico  # Verweist auf die Datei build/favicon.ico
    upload: build/favicon.ico  # Gibt die Datei an, die hochgeladen werden soll

  # Handler für das Logo in der Größe 192x192 Pixel
  - url: /logo192.png
    static_files: build/logo192.png  # Verweist auf die Datei build/logo192.png
    upload: build/logo192.png  # Gibt die Datei an, die hochgeladen werden soll

  # Handler für das Logo in der Größe 512x512 Pixel
  - url: /logo512.png
    static_files: build/logo512.png  # Verweist auf die Datei build/logo512.png
    upload: build/logo512.png  # Gibt die Datei an, die hochgeladen werden soll

  # Handler für die manifest.json Datei
  - url: /manifest.json
    static_files: build/manifest.json  # Verweist auf die Datei build/manifest.json
    upload: build/manifest.json  # Gibt die Datei an, die hochgeladen werden soll

  # Handler für alle anderen URLs, um das Single Page Application (SPA) Routing zu unterstützen
  - url: /.*
    static_files: build/index.html  # Verweist auf die Datei build/index.html
    upload: build/index.html  # Gibt die Datei an, die hochgeladen werden soll
