# Specifies the runtime environment for the app
runtime: python310

# Defines environment variables
env_variables:
  NODE_ENV: 'production'
  PUBLIC_URL: '/'

# Defines the instance class for the application
instance_class: F2

# Handlers for various URL paths and static files
handlers:
  # Handler for the static folder
  - url: /static
    static_dir: build/static

  # Handler for static JavaScript files
  - url: /static/js
    static_dir: build/static/js

  # Handler for static CSS files
  - url: /static/css
    static_dir: build/static/css

  # Handler for static media files
  - url: /static/media
    static_dir: build/static/media

  # Handler for the favicon.ico file
  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico

  # Handler for the logo 192x192 file
  - url: /logo192.png
    static_files: build/logo192.png
    upload: build/logo192.png

  # Handler for the logo 512x512 file
  - url: /logo512.png
    static_files: build/logo512.png
    upload: build/logo512.png

  # Handler for the manifest.json file
  - url: /manifest.json
    static_files: build/manifest.json
    upload: build/manifest.json

  # Handler for LogoIcon.png file
  - url: /LogoIcon.png
    static_files: build/LogoIcon.png
    upload: build/LogoIcon.png

  # Handler for Logo.png file
  - url: /Logo.png
    static_files: build/Logo.png
    upload: build/Logo.png

  # Handler for all other URLs to support Single Page Application (SPA) routing
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
